#
# Pandora utility makefile <- Last updated: Wed Mar 19 22:20:56 2014 -> SGK
#
FFLAGS = 
FC = pgf77
#
PAN = ../pan
SYS = ../sys
ZOO = ../zoo
#
all: cents.x dimes.x he1diff.x modup.x ready.x wrap.x census.x lookat.x
#
include Makefile.inc
